export type PdfLanguage = "en" | "hi";

export interface PrescriptionTranslations {
  documentTitle: string;
  doctorRegNo: string;
  doctorSpecialty: string;
  patient: string;
  age: string;
  gender: string;
  mrn: string;
  phone: string;
  date: string;
  address: string;
  token: string;
  abha: string;
  allergies: string;
  noAllergies: string;
  chronicConditions: string;
  chiefComplaint: string;
  diagnosis: string;
  vitalsTitle: string;
  bp: string;
  pulse: string;
  temp: string;
  weight: string;
  height: string;
  bmi: string;
  spo2: string;
  rxTitle: string;
  medIndex: string;
  medName: string;
  dosage: string;
  route: string;
  frequency: string;
  duration: string;
  instructions: string;
  adviceTitle: string;
  followUpTitle: string;
  doctorSignature: string;
  disclaimer: string;
}

export interface ReceiptTranslations {
  documentTitle: string;
  invoiceNo: string;
  date: string;
  token: string;
  patientInfoTitle: string;
  doctorInfoTitle: string;
  patientName: string;
  mrn: string;
  ageGender: string;
  contact: string;
  address: string;
  doctorName: string;
  specialty: string;
  regNo: string;
  vitalsTitle: string;
  bp: string;
  pulse: string;
  temp: string;
  weight: string;
  spo2: string;
  heightBmi: string;
  clinicalTitle: string;
  chiefComplaint: string;
  diagnosis: string;
  tableIndex: string;
  tableDesc: string;
  tableSac: string;
  tableAmount: string;
  paymentTitle: string;
  statusPaid: string;
  paymentMode: string;
  subtotal: string;
  taxRate: string;
  taxAmount: string;
  totalPaid: string;
  terms: string;
  authorizedSignatory: string;
}

export const PRESCRIPTION_I18N: Record<PdfLanguage, PrescriptionTranslations> = {
  en: {
    documentTitle: "MEDICAL PRESCRIPTION",
    doctorRegNo: "Reg. No:",
    doctorSpecialty: "Specialty:",
    patient: "Patient",
    age: "Age",
    gender: "Gender",
    mrn: "UHID / MRN",
    phone: "Phone",
    date: "Date",
    address: "Address",
    token: "Token #",
    abha: "ABHA ID",
    allergies: "Known Allergies",
    noAllergies: "No Known Drug Allergies (NKDA)",
    chronicConditions: "Chronic Conditions",
    chiefComplaint: "Chief Complaints",
    diagnosis: "Diagnosis",
    vitalsTitle: "Patient Vitals Recorded",
    bp: "BP",
    pulse: "Pulse",
    temp: "Temp",
    weight: "Weight",
    height: "Height",
    bmi: "BMI",
    spo2: "SpO2",
    rxTitle: "Prescribed Medicines (Rx)",
    medIndex: "#",
    medName: "Medicine Name",
    dosage: "Dosage",
    route: "Route",
    frequency: "Frequency",
    duration: "Duration",
    instructions: "Instructions",
    adviceTitle: "General Advice & Precautions",
    followUpTitle: "Next Follow-up / Review",
    doctorSignature: "Doctor's Signature",
    disclaimer:
      "Valid medical prescription generated by OPD system. Take medicines strictly as directed.",
  },
  hi: {
    documentTitle: "चिकित्सीय परामर्श व दवा पर्चा (PRESCRIPTION)",
    doctorRegNo: "पंजीकरण क्र.:",
    doctorSpecialty: "विशेषज्ञता:",
    patient: "मरीज़ का नाम",
    age: "उम्र",
    gender: "लिंग",
    mrn: "विशिष्ट पहचान (UHID / MRN)",
    phone: "मोबाइल नं.",
    date: "परामर्श दिनांक",
    address: "मरीज़ का पता",
    token: "टोकन संख्या",
    abha: "आभा आईडी (ABHA)",
    allergies: "दवा एलर्जी (Allergies)",
    noAllergies: "कोई ज्ञात दवा एलर्जी नहीं (NKDA)",
    chronicConditions: "पुरानी बीमारियाँ / पूर्व इतिहास",
    chiefComplaint: "मुख्य समस्या / लक्षण",
    diagnosis: "निदान (Diagnosis)",
    vitalsTitle: "शारीरिक माप एवं वाइटल्स (Vitals)",
    bp: "रक्तचाप (BP)",
    pulse: "नाड़ी (Pulse)",
    temp: "तापमान (Temp)",
    weight: "वजन (Weight)",
    height: "कद (Height)",
    bmi: "बीएमआई (BMI)",
    spo2: "ऑक्सीजन (SpO2)",
    rxTitle: "निर्धारित दवाइयाँ (Rx - Medicines)",
    medIndex: "#",
    medName: "दवा का नाम (Medicine)",
    dosage: "खुराक (Dosage)",
    route: "मार्ग (Route)",
    frequency: "सेवन समय (Frequency)",
    duration: "अवधि (Duration)",
    instructions: "विशेष निर्देश (Instructions)",
    adviceTitle: "सामान्य परामर्श एवं सावधानियां (Advice)",
    followUpTitle: "अगला परामर्श / फॉलो-अप (Follow-up)",
    doctorSignature: "चिकित्सक के हस्ताक्षर (Doctor's Signature)",
    disclaimer:
      "यह कंप्यूटर द्वारा उत्पन्न अधिकृत चिकित्सीय पर्चा है। दवाइयों का सेवन दिए गए निर्देशानुसार ही करें।",
  },
};

export const RECEIPT_I18N: Record<PdfLanguage, ReceiptTranslations> = {
  en: {
    documentTitle: "TAX INVOICE & RECEIPT",
    invoiceNo: "Invoice No:",
    date: "Date:",
    token: "Token #:",
    patientInfoTitle: "Patient Information",
    doctorInfoTitle: "Consulting Doctor",
    patientName: "Name:",
    mrn: "UHID / MRN:",
    ageGender: "Age / Sex:",
    contact: "Contact:",
    address: "Address:",
    doctorName: "Doctor:",
    specialty: "Specialty:",
    regNo: "Reg. No:",
    vitalsTitle: "Clinical Vitals Recorded at Visit",
    bp: "BP",
    pulse: "Pulse",
    temp: "Temp",
    weight: "Weight",
    spo2: "SpO2",
    heightBmi: "Height / BMI",
    clinicalTitle: "Clinical Summary",
    chiefComplaint: "Complaint:",
    diagnosis: "Diagnosis:",
    tableIndex: "#",
    tableDesc: "Description / Service Item",
    tableSac: "SAC / HSN",
    tableAmount: "Amount (INR)",
    paymentTitle: "Settlement Details",
    statusPaid: "PAID & SETTLED",
    paymentMode: "Payment Mode:",
    subtotal: "Subtotal / Taxable:",
    taxRate: "GST Rate:",
    taxAmount: "GST / Taxes:",
    totalPaid: "Total Paid Amount:",
    terms:
      "1. This is a computer generated official tax invoice and receipt.\n2. Consultation and medical fees once paid are non-refundable.\n3. Please retain this receipt for tax, mediclaim, or insurance reimbursement purposes.",
    authorizedSignatory: "Authorized Signatory",
  },
  hi: {
    documentTitle: "कर चालान एवं भुगतान रसीद (TAX INVOICE & RECEIPT)",
    invoiceNo: "चालान क्र.:",
    date: "दिनांक:",
    token: "टोकन क्र.:",
    patientInfoTitle: "मरीज़ का विवरण (Patient Info)",
    doctorInfoTitle: "परामर्शदाता चिकित्सक (Doctor)",
    patientName: "मरीज़ का नाम:",
    mrn: "यूएचआईडी (UHID / MRN):",
    ageGender: "उम्र / लिंग:",
    contact: "मोबाइल नं.:",
    address: "मरीज़ का पता:",
    doctorName: "चिकित्सक:",
    specialty: "विभाग / विशेषता:",
    regNo: "पंजीकरण संख्या:",
    vitalsTitle: "परामर्श के समय दर्ज शारीरिक माप (Vitals)",
    bp: "रक्तचाप (BP)",
    pulse: "नाड़ी (Pulse)",
    temp: "तापमान (Temp)",
    weight: "वजन (Weight)",
    spo2: "ऑक्सीजन (SpO2)",
    heightBmi: "कद / बीएमआई",
    clinicalTitle: "चिकित्सीय विवरण (Clinical Summary)",
    chiefComplaint: "मुख्य समस्या:",
    diagnosis: "निदान (Diagnosis):",
    tableIndex: "#",
    tableDesc: "सेवा / मद का विवरण (Service / Item)",
    tableSac: "एसएसी कोड (SAC)",
    tableAmount: "राशि (₹ Amount)",
    paymentTitle: "भुगतान का विवरण (Payment Details)",
    statusPaid: "✓ पूर्ण भुगतान प्राप्त (PAID)",
    paymentMode: "भुगतान का माध्यम:",
    subtotal: "उप-कुल (कर-योग्य):",
    taxRate: "जीएसटी दर:",
    taxAmount: "जीएसटी राशि:",
    totalPaid: "कुल प्राप्त राशि:",
    terms:
      "1. यह एक कंप्यूटर द्वारा उत्पन्न अधिकृत वैध कर चालान एवं रसीद है।\n2. परामर्श एवं सेवा शुल्क गैर-वापसी योग्य हैं।\n3. कृपया मेडिक्लेम, बीमा या टैक्स प्रतिपूर्ति हेतु इस रसीद को संभाल कर रखें।",
    authorizedSignatory: "अधिकृत हस्ताक्षरकर्ता",
  },
};

/**
 * Translates common gender strings into Hindi if needed.
 */
export function translateGender(gender?: string | null, lang: PdfLanguage = "en"): string {
  if (!gender) return "—";
  const g = gender.toLowerCase().trim();
  if (lang === "hi") {
    if (g === "male" || g === "m") return "पुरुष (Male)";
    if (g === "female" || g === "f") return "महिला (Female)";
    if (g === "other" || g === "o") return "अन्य (Other)";
  }
  return gender.charAt(0).toUpperCase() + gender.slice(1);
}

/**
 * Translates payment mode into Hindi if needed.
 */
export function translatePaymentMode(mode?: string | null, lang: PdfLanguage = "en"): string {
  if (!mode) return "—";
  const m = mode.toLowerCase().trim();
  if (lang === "hi") {
    if (m === "cash") return "नकद (Cash)";
    if (m === "upi") return "यूपीआई / क्यूआर (UPI)";
    if (m === "card") return "कार्ड (Debit / Credit Card)";
    if (m === "online") return "ऑनलाइन बैंकिंग (Net Banking)";
    if (m === "other") return "बीमा / अन्य (Insurance / Other)";
  }
  return mode.toUpperCase();
}

/**
 * Translates common medical frequency codes into helpful Hindi/English explanation.
 */
export function translateFrequency(freq?: string | null, lang: PdfLanguage = "en"): string {
  if (!freq) return "—";
  if (lang !== "hi") return freq;

  const f = freq.trim();
  if (f === "1-0-1") return "1-0-1 (सुबह - रात)";
  if (f === "1-0-0") return "1-0-0 (सुबह)";
  if (f === "0-0-1") return "0-0-1 (रात)";
  if (f === "0-1-0") return "0-1-0 (दोपहर)";
  if (f === "1-1-1") return "1-1-1 (सुबह - दोपहर - रात)";
  if (/once daily/i.test(f)) return "दिन में एक बार (Once daily)";
  if (/twice daily/i.test(f)) return "दिन में दो बार (Twice daily)";
  if (/thrice daily|three times daily/i.test(f)) return "दिन में तीन बार (Three times daily)";
  if (/as needed|sos/i.test(f)) return "आवश्यकतानुसार (SOS / As needed)";
  if (/bedtime/i.test(f)) return "सोते समय (Bedtime)";
  return f;
}
