/** Common clinic specialties for public listing / discovery filters. */
export const CLINIC_SPECIALTIES = [
  "General medicine",
  "General surgery",
  "Family medicine",
  "Pediatrics",
  "Obstetrics & gynecology",
  "Orthopedics",
  "Cardiology",
  "Dermatology",
  "ENT",
  "Ophthalmology",
  "Dentistry",
  "Neurology",
  "Neurosurgery",
  "Psychiatry",
  "Pulmonology",
  "Gastroenterology",
  "Nephrology",
  "Urology",
  "Endocrinology",
  "Oncology",
  "Rheumatology",
  "Diabetology",
  "Physiotherapy",
  "Ayurveda",
  "Homeopathy",
  "Emergency medicine",
  "Anesthesiology",
  "Radiology",
  "Pathology",
  "Allergy & immunology",
] as const;

export type ClinicSpecialty = (typeof CLINIC_SPECIALTIES)[number];
